core/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
	path('', views.index, name='index'),
]

fornecedores/urls.py
from django.urls import path

from . import views

app_name = 'fornecedores'
urlpatterns = [
    path('cadastro/', views.cadastro, name='cadastro'),
]

pregao/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
	path('', TemplateView.as_view(template_name='index.html'), name='index'),
	path('', include('core.urls')),
	path('usuarios/', include('users.urls')),
	path('usuarios/', include('django.contrib.auth.urls')),
	path('fornecedores/', include('fornecedores.urls', namespace='fornecedores')),
    path('admin/', admin.site.urls),
]

fornecedores/models.py
from django.db import models

class FornecedorManager(models.Manager):
	def search (self, query):
		return self.get_queryset().filter(models.Q(nomefantasia__icontains=query) | models.Q(cnpj__icontains=query))

class Fornecedor(models.Model):
	cnpj = models.CharField('CNPj', max_length=100)
	inscricaoestadual = models.CharField('Inscrição Estadual', max_length=100)
	razaosocial = models.CharField('Razão Social', max_length=100)
	nomefantasia = 	models.CharField('Nome Fantasia', max_length=100)
	email = models.EmailField('Email')
	telefone = models.CharField('Telefone', max_length=11)
	endereco = models.CharField('Endereco', max_length=100)
	cep = models.CharField('CEP', max_length=8)
	estado = models.CharField('Estado', max_length=100)
	cidade = models.CharField('Cidade', max_length=100)
	microempresa = models.CharField('Micro-Empresa', max_length=3)

	def __str__(self):
		return self.nomefantasia

fornecedores/forms.py
from django import forms

MICROEMPRESAOPCOES = (('SIM', 'Sim',), ('NAO', 'Não',))
ESTADOS = (
		('AC', 'Acre'),
		('AL', 'Alagoas'),
		('AP', 'Amapá'),
		('AM', 'Amazonas'),
		('BA', 'Bahia'),
		('CE', 'Ceará'),
		('DF', 'Distrito Federal'),
		('ES', 'Espírito Santo'),
		('GO', 'Goiás'),
		('MA', 'Maranhão'),
		('MT', 'Mato Grosso'),
		('MS', 'Mato Grosso do Sul'),
		('MG', 'Minas Gerais'),
		('PA', 'Pará'),
		('PB', 'Paraíba'),
		('PR', 'Paraná'),
		('PE', 'Pernambuco'),
		('PI', 'Piauí'),
		('RJ', 'Rio de Janeiro'),
		('RN', 'Rio Grande do Norte'),
		('RS', 'Rio Grande do Sul'),
		('RO', 'Rondônia'),
		('RR', 'Roraima'),
		('SC', 'Santa Catarina'),
		('SP', 'São Paulo'),
		('SE', 'Sergipe'),
		('TO', 'Tocantins'),
		)


class FornecedoresForm(forms.Form):

	cnpj = forms.CharField(label='CNPj', max_length=100)
	inscricaoestadual = forms.CharField(label='Inscrição Estadual', max_length=100)
	razaosocial = forms.CharField(label='Razão Social', max_length=100)
	nomefantasia = 	forms.CharField(label='Nome Fantasia', max_length=100)
	email = forms.EmailField(label='Email')
	telefone = forms.CharField(label='Telefone', max_length=11)
	endereco = forms.CharField(label='Endereco', max_length=100)
	cep = forms.CharField(label='CEP', max_length=8)
	estado = forms.CharField(label='Estado', max_length=100, widget=forms.Select(choices=ESTADOS))
	cidade = forms.CharField(label='Cidade', max_length=100)
	microempresa = forms.ChoiceField(label='Micro-Empresa', widget=forms.RadioSelect, choices=MICROEMPRESAOPCOES)

fornecedores/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import FornecedoresForm
from django.http import HttpResponseRedirect
from .models import Fornecedor
from django.contrib.auth.decorators import login_required

#@login_required
def cadastro(request):
	form = FornecedoresForm()
	if request.method == 'POST':
		form = FornecedoresForm(request.POST)
		if form.is_valid():
			dados = form.cleaned_data
			fornecedor = Fornecedor(cnpj=dados['cnpj'], inscricaoestadual=dados['inscricaoestadual'],
				razaosocial=dados['razaosocial'], nomefantasia=dados['nomefantasia'], email=dados['email'],
				telefone=dados['telefone'], endereco=dados['endereco'], cep=dados['cep'], estado=dados['estado'],
				cidade=dados['cidade'], microempresa=dados['microempresa'])
			fornecedor.save()
			return HttpResponseRedirect("")
		else:
			form = FornecedoresForm()

	return render(request, 'fornecedores/cadastro.html', {'form': form})

templates/base.html
<!doctype html>
<html class="no-js" lang="pt-br">
<head>
  {% load static %}
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Pregão - Prefeitura Municipal de Campina Grande</title>
  <link rel="stylesheet" href="{% static 'css/foundation.css' %}">
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
  <link rel="stylesheet" href="{% static 'css/foundation-icons.css' %}">
  <link href='https://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css' rel='stylesheet' type='text/css'>
  <link rel="icon" href="{% static 'img/cropped-Brasão_de_Campina_Grande_-_PB.svg_-32x32.png' %}" sizes="32x32" />
  <link rel="icon" href="{% static 'img/cropped-Brasão_de_Campina_Grande_-_PB.svg_-192x192.png' %}" sizes="192x192" />
  <link rel="apple-touch-icon-precomposed" href="{% static 'img/cropped-Brasão_de_Campina_Grande_-_PB.svg_-180x180.png' %}" />
</head>
<body>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-2195009-2', 'auto');
    ga('send', 'pageview');

    ga('create', 'UA-2195009-27', 'auto', {name: "foundation"});
    ga('foundation.send', 'pageview');

  </script>  <div class="title-bar" data-responsive-toggle="realEstateMenu" data-hide-for="small">
    <button class="menu-icon" type="button" data-toggle></button>
    <div class="title-bar-title">Menu</div>
  </div>
  
  <div class="top-bar" id="realEstateMenu">
    <div class="top-bar-left">
      <ul class="menu" data-responsive-menu="accordion">
        <li class="menu-text">Pregão</li>
        <li><a class="pref-link" href="{% url 'index' %}"><strong>Página Inicial</strong></a></li>
        <li><a class="pref-link" href="{% url 'fornecedores:cadastro' %}"><strong>Fornecedores</strong></a></li>
        <li><a class="pref-link" href="#"><strong>Pregão</strong></a></li>
        <li><a class="pref-link" href="#"><strong>Relatórios</strong></a></li>
        
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        {% if user.is_authenticated %}
        <li><a class="pref-link">Bem vindo, {{ user.username }}</a></li>
        <li><a class="button" href="{% url 'logout' %}">Sair</a></li>
        {% else %}
        <li><a class="pref-link">Olá visitante, favor entre no sistema</a></li>
        <li><a class="button" href="{% url 'login' %}">Entrar</a></li>
        {% endif %}
      </ul>
    </div>
  </div>



  {% block content %}{% endblock %}

  <footer class="footer pref-link">
    <div class="row">
      <div class="medium-6 columns">
        <ul class="menu float-right">
          <li class="menu-text">Secretaria de Administração</li>
        </ul>
      </div>
    </div>
  </footer>
  <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
  <script src="https://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.js"></script>
  <script>
    $(document).foundation();
  </script>
</body>
</html>

templates/fornecedores.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="column large">
  <div class="row column">
    <h2 class="text-center">Cadastro de fornecedor</h2>
    <p class="lead">Preencha os dados abaixo:</p>
    <ul class="tabs" data-deep-link="true" data-update-history="true" data-deep-link-smudge="true" data-deep-link-smudge="500" data-tabs id="deeplinked-tabs">
      <li class="tabs-title is-active"><a href="#juridica" aria-selected="true">Pessoa Jurídica</a></li>
      <li class="tabs-title"><a href="#fisica">Pessoa Física</a></li>
    </ul>

    <div class="tabs-content" data-tabs-content="deeplinked-tabs">
      <div class="tabs-panel is-active" id="juridica">
        <form>
          <div class="row">
            <div class="small-12 medium-3 columns">
              <label>CNPJ:
                <input type="text">
              </label>
            </div>
            <div class="small-12 medium-3 columns">
              <label>Inscrição Estadual:
                <input type="text">
              </label>
            </div>
            <div class="small-12 medium-6 columns">
              <label>Razão Social:
                <input type="text">
              </label>
            </div>
          </div>
          <div class="row">
            <div class="small-12 medium-6 columns">
              <label>Nome Fantasia
                <input type="text">
              </label>
            </div>
            <div class="small-12 medium-3 columns">
              <label>Email
                <input type="email">
              </label>
            </div>
            <div class="small-12 medium-3 columns">
              <label>Telefone
                <input type="tel">
              </label>
            </div>
          </div>
          <div class="row">
            <div class="small-12 medium-9 columns">
              <label>Endereco
                <input type="text">
              </label>
            </div>
            <div class="small-12 medium-3 columns">
              <label>CEP
                <input type="text">
              </label>
            </div>
          </div>
          <div class="row">
            <div class="small-12 medium-2 columns">
              <label>Estado
                <select>
                  <option value="PB">Paraíba</option>
                  <option value="PE">Pernambuco</option>
                  <option value="RN">Rio Grande do Norte</option>
                  <option value="CE">Ceará</option>
                </select>
              </label>
            </div>
            <div class="small-12 medium-8 columns end">
              <label>Cidade
                <input type="text">
              </label>
            </div>
          </div>
          <div class="row">
            <div class="large-3 columns end">
              <fieldset class="fieldset">
                <legend>Micro-Empresa</legend>
                <input type="radio" name="me" value="yes" id="me-yes" required><label for="me-yes">Sim</label>
                <input type="radio" name="me" value="no" id="me-no" checked><label for="me-no">Não</label>
              </fieldset>
            </div>
          </div>
          <div class="row">
            <div class="large-6 columns">
              <p><a class="button small expanded" href="#">Cadastrar</a></p>
            </div>
            <div class="large-6 columns">
              <p><a class="button secondary small expanded" href="#">Cancelar</a></p>
            </div>
          </div>
        </form>
      </div>
      <div class="tabs-panel" id="fisica">
        <p>Pessoa Física.</p>
      </div>
    </div>
  </div>
</div>
{% endblock %}


templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class=" valign-middle row expanded columns background">
  {% load static %}
  <img src="{% static 'img/logo-prefeitura-campinagrande.png' %}" class="float-center">`
</div>

{% endblock %}  